apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-march-app-hpa
  labels:
    app: test-march-app
    version: 0.0.1
    backstage.io/kubernetes-id: test-march-app
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: test-march-app
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75